---
title: "Race and Age vs. NMU"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("two_var_relationship.R")
race_age <- two_var_relationship("DEM_AGE10", "DEM_RACE")
for (i in seq_along(race_age)) {
  cor_heatmap <- ggplot(data = race_age[[i]], aes(x = DEM_AGE10, y = DEM_RACE, fill = NMU)) +
    geom_tile()
  cor_heatmap <- cor_heatmap +
    scale_fill_gradient2(low = "white", high = "darkred", space = "Lab", name="Correlation") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1)) +
    ggtitle(names(race_age)[i])
  print(cor_heatmap)
}
```

# EMU
```{r}
race_age <- two_var_relationship("DEM_AGE10", "DEM_RACE")
for (i in seq_along(race_age)) {
  cor_heatmap <- ggplot(data = race_age[[i]], aes(x = DEM_AGE10, y = DEM_RACE, fill = NMU)) +
    geom_tile()
  cor_heatmap <- cor_heatmap +
    scale_fill_gradient2(low = "white", high = "darkred", space = "Lab", name="Correlation") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1)) +
    ggtitle(names(race_age)[i])
  print(cor_heatmap)
}
```


